/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.*;
import java.io.ByteArrayOutputStream;
import java.io.PrintStream;
import org.junit.After;
import org.junit.Before;
import java.net.*;
import java.lang.*;
import java.util.*;
import java.io.*;
import org.w3c.dom.*;
import java.nio.charset.StandardCharsets;

public class AppTest {

    private final ByteArrayOutputStream outContent = new ByteArrayOutputStream();

    @Before
    public void setUpStreams() {
        System.setOut(new PrintStream(outContent));
    }

    @After
    public void cleanUpStreams() {
        System.setOut(System.out);
    }

    @Test
    public void getメソッドの通信を確認() {

        try {
            URL url = new URL("https://httpbin.org/get");
            App classUnderTest = new App(url);
            classUnderTest.get();
        }
        catch (MalformedURLException e){}


        final String expected = "HTTPステータス:200";
        final String ac = outContent.toString();
        final String[] actual = ac.split("\n");

        assertEquals(expected, actual[0]);
    }

    @Test
    public void downloadメソッドの通信を確認() {

        try {
            URL url = new URL("https://httpbin.org/image/png");
            App classUnderTest = new App(url);
            classUnderTest.download("file/image.png");
        }
        catch (MalformedURLException e){}

        final String expected = "HTTPステータス:200";
        final String ac = outContent.toString();
        final String[] actual = ac.split("\n");

        assertEquals(expected, actual[0]);
    }

    @Test
    public void headerメソッドの通信を確認() {

        try {
            URL url = new URL("https://httpbin.org/get");
            App classUnderTest = new App(url);
            classUnderTest.header();
        }
        catch (MalformedURLException e){}

        final String expected = "HTTPステータス:200";
        final String ac = outContent.toString();
        final String[] actual = ac.split("\n");

        assertEquals(expected, actual[0]);
    }

    @Test
    public void postメソッドの通信を確認() {

        try {
            URL url = new URL("https://httpbin.org/post");
            App classUnderTest = new App(url);
            classUnderTest.post();
        }
        catch (MalformedURLException e){}

        final String expected = "HTTPステータス:200";
        final String ac = outContent.toString();
        final String[] actual = ac.split("\n");

        assertEquals(expected, actual[0]);
    }

    @Test
    public void postoutメソッドの通信を確認() {

        try {
            URL url = new URL("https://httpbin.org/post");
            App classUnderTest = new App(url);
            classUnderTest.postout("key=value");
        }
        catch (MalformedURLException e){}

        final String expected = "HTTPステータス:200";
        final String ac = outContent.toString();
        final String[] actual = ac.split("\n");

        assertEquals(expected, actual[0]);
    }
}
